name: .NET 5 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300
    - name: Test secret
      env:
        SUPER_SECRET: ${{ secrets.TESTSECRET }}
      if:  env.SUPER_SECRET == 'Hello World'
      run: echo "I know what the secret token is!"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
