name: .NET 5 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300
    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "/home/runner/work/LidlApi/LidlApi/UnitTest/app.config"
        FILE_DATA: |
                    <?xml version="1.0" encoding="utf-8"?>
                    <configuration>
                      <appSettings>
                        <!-- E-mail address to log in with for the Lidl App to run the unit tests -->
                        <add key="EmailAddress" value="${{ secrets.LIDLPLUSEMAILADDRESS }}"/>
                        <!-- Password to log in with for the Lidl App to run the unit tests -->
                        <add key="Password" value="${{ secrets.LIDLPLUSPASSWORD }}"/>
                        <!-- RefreshToken to log in with for the Lidl App to run the unit tests -->
                        <add key="RefreshToken" value=""/>
                      </appSettings>
                    </configuration>
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
