name: .NET 5 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300 
    - name: Create config file 
      run: echo '<?xml version="1.0" encoding="utf-8"?>
                    <configuration>
                      <appSettings>
                        <add key="EmailAddress" value="${{ secrets.LIDLPLUSEMAILADDRESS }}"/>
                        <add key="Password" value="${{ secrets.LIDLPLUSPASSWORD }}"/>
                        <add key="RefreshToken" value=""/>
                      </appSettings>
                    </configuration>' > ./UnitTest/app.config
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      if: ${{ false }}
      run: dotnet test --no-restore --verbosity minimal
